### ISSUE TITLE
Emacs terminal version, all-the-icons

### ISSUE THREAD

**Issue by UtamaruMonster** [sebastiencs/icons-in-terminal#3]
Good day.

Can you show me how to make icons-in-terminal work in Emacs terminal version with all-the-icons and etc...

Thank you.

P.S. please label this as **question**

**Comment by sebastiencs** [comment]
Hello @UtamaruMonster 

icons-in-terminal is not related to all-the-icons and it's not compatible, sorry.
What feature do you need from all-the-icons based project ?

You can take a look at [sidebar.el](https://github.com/sebastiencs/sidebar.el), a project i'm working on. It's working on emacs terminal and GUI with icons-in-terminal.

**Comment by UtamaruMonster** [comment]
Hi.

What i wanted is to use the icons-in-terminal for neotree. I will take a look at sidebar, looks cool.

**Comment by sebastiencs** [comment]
@UtamaruMonster The package is soon available on melpa: https://github.com/melpa/melpa/pull/4884.  
Hope you like it :)
